name: Landscape UI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: NPM install
        run: npm install

      - name: Prettier format
        run: npx prettier . --check

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build --tag landscape:latest . --progress=plain --build-arg="PORT=4200"

      - name: Push image to dockerhub
        run: |
          docker image tag landscape:latest emmanuelu17/landscape:latest
          docker push --all-tags emmanuelu17/landscape
